apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: aws-secrets-manager
  annotations:
    argocd.argoproj.io/sync-wave: "1"   # operator Application is wave "0" by default
spec:
  provider:
    aws:
      service: SecretsManager
      region: eu-central-1
