apiVersion: v1
kind: Secret
metadata:
  name: alertmanager-slack-prod
  namespace: monitoring
  labels:
    app: kube-prometheus-stack-alertmanager
    release: kube-prometheus-stack
stringData:
  webhook_url: ""  #replace with external secret manager referencetype: Opaque
---
apiVersion: monitoring.coreos.com/v1alpha1
kind: AlertmanagerConfig
metadata:
  name: petclinic-alertmanager-prod
  namespace: monitoring
  labels:
    release: kube-prometheus-stack
spec:
  route:
    receiver: slack-prod
    groupBy: ['alertname', 'namespace', 'severity']
    groupWait: 30s
    groupInterval: 5m
    repeatInterval: 1h
    matchers:
      - name: environment
        matchType: '='
        value: "petclinic-prod"
  receivers:
    - name: slack-prod
      slackConfigs:
        - apiURL:
            name: alertmanager-slack-prod
            key: webhook_url
          channel: '#alerts'
          sendResolved: true
          text: '{{ template "slack.default.text" . }}'
          title: '{{ template "slack.default.title" . }}'