apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: petclinic-prod-monitor
  namespace: monitoring
  labels:
    release: kube-prometheus-stack      #read every ServiceMonitor in the cluster labeled kube-prometheus-stack
spec:
  jobLabel: app
  namespaceSelector:
    matchNames:
      - petclinic-prod  #look for services inside the petclinic-prod namespace
  selector:
    matchLabels:    #Kubernetes Service object whose labels match
      app.kubernetes.io/name: myapp                   #name=myapp
      app.kubernetes.io/instance: petclinic-prod      #instance=petclinic-prod
  endpoints:
    - port: http
      path: /actuator/prometheus
      interval: 15s
      scrapeTimeout: 10s
      relabelings:
        - sourceLabels: [__meta_kubernetes_namespace]
          targetLabel: environment
        - sourceLabels: [__meta_kubernetes_service_name]
          targetLabel: service
        - sourceLabels: [__meta_kubernetes_pod_name]
          targetLabel: pod