apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus-stack
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:                          # multi-source app: remote chart + your values file
    - repoURL: https://prometheus-community.github.io/helm-charts
      chart: kube-prometheus-stack
      targetRevision: "62.7.0"      # prometheus_chart_version
      helm:
        valueFiles:
          - $values/argocd/prometheus/values.yaml
    - repoURL: https://github.com/mostafagheta/final_project.git
      targetRevision: dev
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring           # prometheus_namespace
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
